Verify marketplace annotation
This commit adds a marketplace specific validation that checks required
marketplace annotation. The validation is done in ci and hosted
pipelines.

This commit also creates new tasks that were originally part of
different tasks. This is a refactor to avoid duplicated code an
unnecessary API calls.

JIRA: ISV-1366

diff --git a/ansible/roles/operator-pipeline/templates/openshift/tasks/annotations-validation.yml b/ansible/roles/operator-pipeline/templates/openshift/tasks/annotations-validation.yml
--- a/ansible/roles/operator-pipeline/templates/openshift/tasks/annotations-validation.yml
+++ b/ansible/roles/operator-pipeline/templates/openshift/tasks/annotations-validation.yml
@@ -4,12 +4,23 @@ kind: Task
 metadata:
   name: annotations-validation
 spec:
+  description: >-
+    This task verifies bundle annotation.
   params:
     - name: pipeline_image
+      description: The common pipeline image.
+
     - name: bundle_path
-      description: path indicating the location of the certified bundle within the repository
+      description: |
+        Path indicating the location of the certified bundle within the repository.
+
     - name: package_name
-      description: package name defined by the bundle path
+      description: |
+        Package name defined by the bundle path.
+
+    - name: organization
+      description: |
+        Organization defined in the project config.yaml - either certified-operator or redhat-marketplace
   workspaces:
     - name: source
   steps:
@@ -25,4 +36,27 @@ spec:
         if [[ $(params.package_name) != $ANNOTATIONS_PACKAGE_NAME ]]; then
           echo "Package name passed in bundle_path parameter doesn't equal the package name from submitted metadata/annotations.yaml file"
           exit 1
+        fi
+
+        if [[ $(params.organization) == "redhat-marketplace" ]]; then
+
+          MARKETPLACE_REMOTE_WORKFLOW=$(cat $(params.bundle_path)/metadata/annotations.yaml | yq -r '.annotations."marketplace.openshift.io/remote-workflow"')
+          MARKETPLACE_SUPPORT_WORKFLOW=$(cat $(params.bundle_path)/metadata/annotations.yaml | yq -r '.annotations."marketplace.openshift.io/support-workflow"')
+
+          EXPECTED_MARKETPLACE_REMOTE_WORKFLOW="https://marketplace.redhat.com/en-us/operators/$(params.package_name)/pricing?utm_source=openshift_console"
+          EXPECTED_MARKETPLACE_SUPPORT_WORKFLOW="https://marketplace.redhat.com/en-us/operators/$(params.package_name)/support?utm_source=openshift_console"
+
+          if [[ $MARKETPLACE_REMOTE_WORKFLOW != $EXPECTED_MARKETPLACE_REMOTE_WORKFLOW ]]; then
+            echo "Missing or incorrect 'marketplace.openshift.io/remote-workflow' annotation."
+            echo "To fix this issue define the annotation in 'metadata/annotations.yaml' file."
+            echo "The correct value for the annotation is: $EXPECTED_MARKETPLACE_REMOTE_WORKFLOW"
+            exit 1
+          fi
+
+          if [[ $MARKETPLACE_SUPPORT_WORKFLOW != $EXPECTED_MARKETPLACE_SUPPORT_WORKFLOW ]]; then
+            echo "Missing or incorrect 'marketplace.openshift.io/support-workflow' annotation."
+            echo "To fix this issue define the annotation in 'metadata/annotations.yaml' file."
+            echo "The correct value for the annotation is: $EXPECTED_MARKETPLACE_REMOTE_WORKFLOW"
+            exit 1
+          fi
         fi
