[ISV-749] Check whether preflight test_tool version meeting the condi… (#70)
* [ISV-749] Check whether preflight test_tool version meeting the condition of preflight_min_version

* Update the info message

* Fix up the version comparison

* Fix up the version comparison

* Fix up the version comparison

* Add 'failure' as a result when preflight version dosen't meet minimum requirement

* Add 'failure' as a result when preflight version dosen't meet minimum requirement

* Fix up the params value

Co-authored-by: haripate <>

diff --git a/ansible/roles/operator-pipeline/templates/openshift/tasks/verify-ci-results.yml b/ansible/roles/operator-pipeline/templates/openshift/tasks/verify-ci-results.yml
--- a/ansible/roles/operator-pipeline/templates/openshift/tasks/verify-ci-results.yml
+++ b/ansible/roles/operator-pipeline/templates/openshift/tasks/verify-ci-results.yml
@@ -18,12 +18,23 @@ spec:
       image: quay.io/redhat-isv/operator-pipelines-images:latest
       workingDir: $(workspaces.results.path)
       env:
+        - name: PREFLIGHT_MIN_VERSION
+          value: $(params.preflight_min_version)
         - name: PREFLIGHT_RESULTS
           value: $(params.preflight_results)
       script: |
         #! /usr/bin/env bash
         set -xe -o pipefail
 
+        # did preflight/ CI have the latest version?
+        PREFLIGHT_VERSION=$(echo $PREFLIGHT_RESULTS | jq '.test_library.version' |  tr -d '"' | grep .)
+        if [ "$(printf '%s\n' "$PREFLIGHT_MIN_VERSION" "$PREFLIGHT_VERSION" | sort -V | head -n1)" = "$PREFLIGHT_MIN_VERSION" ]; then
+          echo "Preflight version $PREFLIGHT_VERSION satisfies the minimun requirement of version $PREFLIGHT_MIN_VERSION"
+        else
+          echo "Preflight version $PREFLIGHT_VERSION must be $PREFLIGHT_MIN_VERSION or higher."
+          echo "failure" | tee $(results.test_result.path)
+          exit 1
+        fi
         # Did the tests pass?
         # In case of failure- comment on the PR with tailored support link
         CHECK_RESULTS=$(echo $PREFLIGHT_RESULTS | jq '.passed' | tr -d '"' | grep .)
