[ISV-5271] Fail on max retries reached

diff --git a/ansible/roles/index_signature_verification/files/tasks/verify-index-signatures.yml b/ansible/roles/index_signature_verification/files/tasks/verify-index-signatures.yml
--- a/ansible/roles/index_signature_verification/files/tasks/verify-index-signatures.yml
+++ b/ansible/roles/index_signature_verification/files/tasks/verify-index-signatures.yml
@@ -116,8 +116,10 @@ spec:
 
                 sleep $wait_time
                 wait_time=$((wait_time * 2))
-            done
 
-            echo "ERROR: Podman pull failed."
-            exit 1
+                if [ $i -eq $max_retries ]; then
+                    echo "ERROR: Podman pull failed after $max_retries attempts."
+                    exit 1
+                fi
+            done
         done
